server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:mem:authdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "super-secret-key"
  expiration: 86400000
