server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:paymentsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true